import { Text } from "react-native";
import React from "react";
import { View } from "react-native";

const Untitled6 = () => {
  return <View style={{
    backgroundColor: '#f0f0f1',
    padding: 10,
    position: 'relative',
    height: '100%'
  }}>
      <View style={{
      left: 20,
      top: 17,
      position: "absolute",
      height: 99,
      width: 160,
      backgroundColor: "#312fa1",
      borderRadius: 0,
      color: "#777777",
      borderWidth: 2
    }}></View><Text style={{
      left: 20,
      top: 50,
      position: "absolute",
      width: 160,
      height: 50,
      lineHeight: 14,
      fontSize: 14,
      borderRadius: 0,
      textAlign: "center"
    }}>Generated QR Code</Text><View style={{
      left: 20,
      top: 126,
      position: "absolute",
      height: 56,
      width: 113,
      backgroundColor: "#a02f2f",
      borderRadius: 0,
      color: "#777777",
      borderWidth: 2
    }}></View><View style={{
      left: 20,
      top: 208,
      position: "absolute",
      height: 31,
      width: 160,
      backgroundColor: "#2fa135",
      borderRadius: 0,
      color: "#777777",
      borderWidth: 2
    }}></View><Text style={{
      left: 20,
      top: 144,
      position: "absolute",
      width: 114,
      height: 19,
      lineHeight: 14,
      fontSize: 14,
      borderRadius: 0,
      textAlign: "center"
    }}>Emergency</Text><View style={{
      left: 20,
      top: 242,
      position: "absolute",
      height: 31,
      width: 160,
      backgroundColor: "#2fa135",
      borderRadius: 0,
      color: "#777777",
      borderWidth: 2
    }}></View><View style={{
      left: 20,
      top: 277,
      position: "absolute",
      height: 31,
      width: 160,
      backgroundColor: "#2fa135",
      borderRadius: 0,
      color: "#777777",
      borderWidth: 2
    }}></View><Text style={{
      left: 20,
      top: 214,
      position: "absolute",
      width: 160,
      height: 19,
      lineHeight: 14,
      fontSize: 14,
      borderRadius: 0,
      textAlign: "center"
    }}>Home</Text><Text style={{
      left: 21,
      top: 285,
      position: "absolute",
      width: 160,
      height: 19,
      lineHeight: 14,
      fontSize: 14,
      borderRadius: 0,
      textAlign: "center"
    }}>Medical History</Text><Text style={{
      left: 22,
      top: 249,
      position: "absolute",
      width: 160,
      height: 19,
      lineHeight: 14,
      fontSize: 14,
      borderRadius: 0,
      textAlign: "center"
    }}>Profile</Text><View style={{
      left: 20,
      top: 313,
      position: "absolute",
      height: 31,
      width: 160,
      backgroundColor: "#2fa135",
      borderRadius: 0,
      color: "#777777",
      borderWidth: 2
    }}></View><Text style={{
      left: 19,
      top: 319,
      position: "absolute",
      width: 160,
      height: 19,
      lineHeight: 14,
      fontSize: 14,
      borderRadius: 0,
      textAlign: "center"
    }}>Summary</Text><Text style={{
      left: 20,
      top: 193,
      position: "absolute",
      width: 159,
      height: 14,
      lineHeight: 8,
      fontSize: 14,
      borderRadius: 0,
      textAlign: "center"
    }}>Bottom Menu</Text><View style={{
      left: 140,
      top: 126,
      position: "absolute",
      height: 55,
      width: 40,
      backgroundColor: "#dda7a7",
      borderRadius: 0,
      color: "#777777"
    }}></View><Text style={{
      left: 144,
      top: 144,
      position: "absolute",
      width: 31,
      height: 22,
      lineHeight: 9,
      fontSize: 14,
      borderRadius: 0
    }}>Settings </Text></View>;
};

export default Untitled6;